#%% ABOUT
# *****************************************************************************
'''
Use this script to create a lean requirements.txt file that lists only the
packages that appear in import statements for a project. This is motivated by
the need to create requirements files that are not platform/OS-specific. Often,
the primary packages used in a project are not platform-specific, but their
dependencies are. By using just the packages that are imported, we remove any
dependencies from the requirements file, and rely on the end user's package
manager (pip or conda) to install the dependencies it needs.

This script can be run at different times in a project's lifecycle to stay up
to date with evolving package use. However, note that:
    - to keep unused packages out of the lean requirements file, the user must
    delete or comment-out import statements for packages that are no longer
    used.
    - to get the latest version numbers for packages that have been added or
    updated, the user must re-create the base requirements.txt before running
    this script.

Features:
    - Ignores standard library imports (e.g., import os)
    - Ignores local imports (e.g., import mylib if mylib.py is also present in the folder)
    - Handles common package name discrepancies (like 'PIL' vs 'pillow')
    - Preserves version specifications from your original requirements file
    - Provides warnings for imports not found in your original requirements file, and:
        - Adds them to the output requirements file (without specifying version)
        - Prints the name(s) of the script(s) using them so you can review

This code was generated by Claude 3.7 on 3/7/2025 with prompting by Justin
Replogle. Link to conversation:
    https://claude.ai/chat/8861617d-f040-43bc-b806-d77b2075ed67

Original prompt:
	Write a python program to do what is written in these comments:
	## Define requirements file to check
	## Define project folder to check
	## Find imports in all .py code files in project folder and subfolders
	## Create lean requirements file by removing everything except the packages imported in code

Additional prompts:
    Add the following feature: if an imported package name contains an underscore,
    search the requirements file for one containing dashes instead.  E.g., import
    langchain_core should match to langchain-core in the requirements.

    Add the following feature: if another local python script is being imported,
    do not show a warning and do not add it to the requirements file.  E.g., a
    script might contain 'import mylib' - if you find another script called
    mylib.py, this is a local import.

    Add the following feature: if a package is found in an import statement but
    not in the requirements file, add to the print statement the name of the
    python script where it was found.

Edits made to the code generated by Claude:
    - JR: Added packages to the list of those in the standard library
    - JR: Slightly modified messages in print statements

Known issues:
    - Import statements inside quotes or block-quotes are handled just like any
    other import. This means:
        - If you want to ignore an import, comment-out the line rather than quoting
        it.
        - Any line starting with "import" or "from" in a block quote will be
        interpreted as an import and the word after it will be added to the output
        requirements file. This will result in an error about package not found
        when someone tries to use the requirements file. Although it's not fatal,
        these should be removed. These will appear as warnings when running this
        program, like so:
            Warning: Package 'XYZ' found in imports but not in requirements.txt
    - Local imports from a subfolder are not recognized as local imports. For
    example, import lib.my_functions where my_functions.py is in subfolder /lib
    will add package 'lib' to the output requirements file and give a warning.
'''
#%% USAGE
# *****************************************************************************
'''
First, use pip to create the requirements.txt file for your Python environment.
Then, in a command console, run:
    python "path/to/this_script.py" -r "path/to/original_requirements.txt" -p "path/to/project_folder" -o "path/to/output_lean_requirements.txt"

Important: if your folder paths contains spaces, you MUST enclose them in
double quotes.

Alternatively, put this script in the same folder as your requirements.txt file
and run it without arguments to use the defaults:
	cd "path/to/this_script"
    python create_lean_requirements.py
	
	This assumes:
    - requirements.txt is in the current directory
    - project files are in the current directory
    - requirements_lean.txt will be created in the current directory
'''
#%% PROGRAM
# *****************************************************************************
import os
import re
import argparse
from pathlib import Path
from collections import defaultdict

def find_imports(file_path):
    """Extract all import statements from a Python file."""
    imports = set()
    import_regex = re.compile(r'^(?:import|from)\s+([a-zA-Z0-9_\.]+)')

    with open(file_path, 'r', encoding='utf-8') as file:
        try:
            for line in file:
                match = import_regex.match(line.strip())
                if match:
                    # Extract just the base package name (before any dots)
                    package = match.group(1).split('.')[0]
                    # Exclude standard library modules
                    if not is_standard_library(package):
                        imports.add(package)
        except UnicodeDecodeError:
            print(f"Warning: Could not read {file_path} due to encoding issues")

    return imports

def is_standard_library(module_name):
    """Check if a module is part of the Python standard library."""
    standard_libs = {
        'abc', 'argparse', 'asyncio', 'collections', 'configparser', 'csv', 'datetime',
        'decimal', 'enum', 'functools', 'glob', 'hashlib', 'io', 'itertools', 'json',
        'logging', 'math', 'multiprocessing', 'os', 'pathlib', 'random', 're', 'shutil',
        'signal', 'socket', 'sqlite3', 'statistics', 'string', 'sys', 'tempfile', 'threading',
        'time', 'typing', 'uuid', 'warnings', 'xml', 'zipfile'
		,'platform'
		,'queue'
		,'inspect'
		,'pickle'
		,'base64'
		,'pkg_resources'
		,'subprocess'
		,'tzlocal'
        ,'gzip'
        ,'pprint'
        ,'netaddr'
        ,'timeit'
        ,'ipaddress'
    }

    return module_name in standard_libs

def find_local_modules(project_path):
    """Find all Python files in the project to identify local modules."""
    local_modules = set()

    for root, _, files in os.walk(project_path):
        for file in files:
            if file.endswith('.py'):
                # Add the module name without the .py extension
                module_name = os.path.splitext(file)[0]
                local_modules.add(module_name)

    return local_modules

def scan_project(project_path):
    """Scan all Python files in a project for imports."""
    all_imports = set()
    import_sources = defaultdict(list)

    for root, _, files in os.walk(project_path):
        for file in files:
            if file.endswith('.py'):
                file_path = os.path.join(root, file)
                try:
                    file_imports = find_imports(file_path)
                    all_imports.update(file_imports)

                    # Track which file imported which package
                    for imported_pkg in file_imports:
                        import_sources[imported_pkg].append(file_path)

                except Exception as e:
                    print(f"Error processing {file_path}: {e}")

    return all_imports, import_sources

def parse_requirements(req_file_path):
    """Parse a requirements.txt file into a dict of {package_name: full_line}."""
    requirements = {}

    if not os.path.exists(req_file_path):
        print(f"Requirements file not found: {req_file_path}")
        return requirements

    with open(req_file_path, 'r') as file:
        for line in file:
            line = line.strip()
            if line and not line.startswith('#'):
                # Handle lines with version specifiers
                package_name = line.split('==')[0].split('>=')[0].split('<=')[0].split('<')[0].split('>')[0].strip()
                requirements[package_name.lower()] = line

    return requirements

def create_lean_requirements(existing_requirements, found_imports, local_modules, import_sources):
    """Create a lean requirements dictionary based on found imports."""
    lean_requirements = {}
    missing_packages = {}

    for package in found_imports:
        package_lower = package.lower()

        # Skip local modules
        if package in local_modules:
            continue

        # Check for direct match
        if package_lower in existing_requirements:
            lean_requirements[package_lower] = existing_requirements[package_lower]
        else:
            # Check for underscore to dash conversion
            if '_' in package_lower:
                dash_package = package_lower.replace('_', '-')
                if dash_package in existing_requirements:
                    lean_requirements[dash_package] = existing_requirements[dash_package]
                    continue

            # Some packages have different import names than PyPI names
            # This is a basic mapping of common cases
            common_mappings = {
                'PIL': 'pillow',
                'sklearn': 'scikit-learn',
                'bs4': 'beautifulsoup4',
                'dotenv': 'python-dotenv',
                'cv2': 'opencv-python',
                'yaml': 'pyyaml'
            }

            if package in common_mappings and common_mappings[package] in existing_requirements:
                lean_requirements[common_mappings[package]] = existing_requirements[common_mappings[package]]
            else:
                # Track missing packages and their source files
                missing_packages[package] = import_sources[package]
                # Add without version as fallback
                lean_requirements[package_lower] = package

    # Print warnings for missing packages with their source files
    for package, sources in missing_packages.items():
        source_files = [os.path.basename(src) for src in sources]
        print(f"Warning: Package '{package}' found in imports but not in requirements.txt")
        print(f"         Used in: {', '.join(source_files)}")

    return lean_requirements

def main():
    parser = argparse.ArgumentParser(description='Create a lean requirements.txt based on actual imports')
    parser.add_argument('-r', '--requirements', default='requirements.txt',
                        help='Path to the requirements file to check')
    parser.add_argument('-p', '--project', default='.',
                        help='Path to the project folder to scan')
    parser.add_argument('-o', '--output', default='requirements_lean.txt',
                        help='Output file for lean requirements')

    args = parser.parse_args()

    req_path = Path(args.requirements)
    project_path = Path(args.project)
    output_path = Path(args.output)

    print(f"Scanning Python files in {project_path}...")
    local_modules = find_local_modules(project_path)
    print(f"Found {len(local_modules)} Python scripts")

    imports, import_sources = scan_project(project_path)
    external_imports = imports - local_modules
    print(f"Found {len(external_imports)} external imported packages: {', '.join(sorted(external_imports))}")
    if local_modules.intersection(imports):
        print(f"Found {len(local_modules.intersection(imports))} local imports: {', '.join(sorted(local_modules.intersection(imports)))}")

    print(f"Parsing requirements file: {req_path}")
    requirements = parse_requirements(req_path)
    print(f"Found {len(requirements)} packages in the requirements file")

    lean_requirements = create_lean_requirements(requirements, external_imports, local_modules, import_sources)
    print(f"Creating lean requirements with {len(lean_requirements)} packages")

    with open(output_path, 'w') as file:
        file.write("# Lean requirements file generated based on actual imports\n")
        for _, req_line in sorted(lean_requirements.items()):
            file.write(f"{req_line}\n")

    print(f"Lean requirements file created at {output_path}")

if __name__ == "__main__":
    main()
